### ISSUE TITLE
Error with Bootstrap 4.1.3 -  Cannot set property 'emulateTransitionEnd' of undefined at setTransitionEndSupport

### ISSUE THREAD

**Issue by dsingh09** [borisding/universsr#4]
Hi, 
Using bootstap v4 with universsr but getting below error.

{"message":"/var/www/html/local.droomvue.in/react/node_modules/bootstrap/dist/js/bootstrap.js:1\nTypeError: Cannot set property 'emulateTransitionEnd' of undefined\n    at setTransitionEndSupport (/var/www/html/local.droomvue.in/react/node_modules/bootstrap/dist/js/bootstrap.js:122:36)\n    at /var/www/html/local.droomvue.in/react/node_modules/bootstrap/dist/js/bootstrap.js:199:5\n    at /var/www/html/local.droomvue.in/react/node_modules/bootstrap/dist/js/bootstrap.js:201:4\n    at /var/www/html/local.droomvue.in/react/node_modules/bootstrap/dist/js/bootstrap.js:7:66\n    at Object.<anonymous> (/var/www/html/local.droomvue.in/react/node_modules/bootstrap/dist/js/bootstrap.js:10:2)\n    at Object.Module._extensions..js (module.js:654:10)","level":"error"}

**Comment by borisding** [comment]
Hi @dsingh09,

I recommend to use [reactstrap](https://reactstrap.github.io/) for React Bootstrap 4 components instead of using bootstrap.js directly. You may also use [Bloomer](https://bloomer.js.org/#/) if you want to try [Bulma](https://bulma.io/) as alternative.
